Repository paritytech/parity-common, pull requests merged in 2018-08, with the labels that each got.

#13 Fix seek in TrieDB iterator
  patricia_trie/src/lib.rs
  patricia_trie/src/triedb.rs
Labels: A0-pleasereview, M4-core

#10 Add readmes for parity-common crates
  hashdb/README.md
  keccak-hash/README.md
  memorydb/README.md
  triehash/README.md
Labels: A3-inprogress, F5-documentation, M4-core

#15 Misc cleanup and unused deps
  kvdb/src/lib.rs
  plain_hasher/util/plain_hasher/Cargo.toml
  triehash/Cargo.toml
  triehash/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, F5-task

#20 [hashdb] make the `Hasher` trait useable with `no_std`
  .travis.yml
  hashdb/Cargo.toml
  hashdb/README.md
  hashdb/src/lib.rs
  plain_hasher/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, F6-refactor

#18 unbound salt size
  parity-crypto/src/lib.rs
  parity-crypto/src/scrypt.rs
Labels: A0-pleasereview, F6-refactor, M4-core

#25 Port over relevant changes from bigint
  .travis.yml
  uint/Cargo.toml
  uint/README.md
  uint/benches/bigint.rs
  uint/build.rs
  uint/src/lib.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A0-pleasereview, F3-annoyance, M4-core

#6 Fix triehash benchmarks
  triehash/Cargo.toml
  triehash/benches/triehash.rs
Labels: A8-looksgood, F4-tests, M4-core

#31 fix patricia-trie bench compilation
  patricia_trie/Cargo.toml
  patricia_trie/benches/trie.rs
Labels: A8-looksgood, M4-core

#28 Relax version requirements
  memorydb/Cargo.toml
  patricia_trie/Cargo.toml
  triehash/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, F5-task, M4-core

#32 Fix docs, remove outdated comments, remove overflowing divs/rems.
  uint/src/uint.rs
Labels: A8-looksgood

#35 Load ethereum-types to fix benchmarks
  triehash/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, F5-task

#36 Add transaction-pool
  Cargo.toml
  trace-time/Cargo.toml
  trace-time/src/lib.rs
  transaction-pool/Cargo.toml
  transaction-pool/src/error.rs
  transaction-pool/src/lib.rs
  transaction-pool/src/listener.rs
  transaction-pool/src/options.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/ready.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/status.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/tests/tx_builder.rs
  transaction-pool/src/transactions.rs
  transaction-pool/src/verifier.rs
Labels: A2-insubstantial, A6-mustntgrumble, F6-refactor, M5-dependencies

#37 rlp optimization
  rlp/benches/rlp.rs
  rlp/src/rlpin.rs
Labels: A8-looksgood, M4-core

#34 Port over relevant tests and code from parity-hash
  .travis.yml
  fixed-hash/Cargo.toml
  fixed-hash/README.md
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
Labels: A0-pleasereview, F6-refactor, M4-core

#42 Fix scoring to favour lower insertion_ids.
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/mod.rs
Labels: A0-pleasereview, A8-looksgood, M4-core
