Repository paritytech/parity-common, pull requests merged in 2018-07, with the labels that each got.

#4 Prep for publication of triehash v0.2 to crates.io
  path/Cargo.toml
  path/src/lib.rs
  triehash/Cargo.toml
Labels: A8-looksgood

#3 Replace `std::env::home_dir` with `dirs::home_dir` (#9077)
  path/Cargo.toml
  path/src/lib.rs
Labels: A8-looksgood

#7 Upstream changes to kvdb-rocksdb
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial, M5-dependencies

#11 Revert 9077
  path/Cargo.toml
  path/src/lib.rs
Labels: A0-pleasereview, M4-core

#9 Fix bug where deriven Default impl causes panics
  memorydb/Cargo.toml
  memorydb/src/lib.rs
Labels: A2-insubstantial, A8-looksgood, F2-bug, M4-core
