Repository paritytech/parity-common, pull requests merged in 2018-10, with the labels that each got.

#68 Add missing repository tags
  fixed-hash/Cargo.toml
  hashdb/Cargo.toml
  transaction-pool/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#67 Revert some recent changes
  Cargo.toml
  fixed-hash/Cargo.toml
  fixed-hash/src/hash.rs
  hashdb/src/lib.rs
  memorydb/Cargo.toml
  memorydb/src/lib.rs
  patricia_trie/Cargo.toml
  patricia_trie/src/fatdb.rs
  patricia_trie/src/fatdbmut.rs
  patricia_trie/src/triedb.rs
  rlp/Cargo.toml
  rlp/src/rlpin.rs
  rlp/tests/tests.rs
  test-support/patricia-trie-ethereum/Cargo.toml
  triehash/Cargo.toml
Labels: A8-looksgood, M4-core

#72 [fixed-hash] Add deprecations in favor of the upcoming 0.3 major version
  fixed-hash/Cargo.toml
  fixed-hash/src/hash.rs
Labels: A8-looksgood

#71 [fixed-hash] Major overhaul of `construct_hash!` macro
  .travis.yml
  appveyor.yml
  fixed-hash/Cargo.toml
  fixed-hash/README.md
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  fixed-hash/src/tests.rs
Labels: A1-onice, A8-looksgood
