Repository paritytech/parity-common, pull requests merged in 2018-09, with the labels that each got.

#44 Link to paritytech.io in README.md
  README.md
Labels: A2-insubstantial, A8-looksgood, F5-task

#38 Fix removal of storage variable with fatdb.
  patricia_trie/src/fatdbmut.rs
Labels: A8-looksgood, M4-core

#53 Update logging in DB recovery
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood, M4-core

#55 [patricia-tree] version 0.2.2
  patricia_trie/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#40 Refactor OwnedNode::Branch
  patricia_trie/src/node.rs
  patricia_trie/src/triedb.rs
Labels: A8-looksgood, M4-core

#29 rlp: remove elastic-array crate and use Vec instead
  hashdb/Cargo.toml
  hashdb/src/lib.rs
  memorydb/Cargo.toml
  memorydb/benches/memdb.rs
  memorydb/src/lib.rs
  patricia_trie/Cargo.toml
  patricia_trie/benches/trie.rs
  patricia_trie/src/fatdb.rs
  patricia_trie/src/fatdbmut.rs
  patricia_trie/src/lib.rs
  patricia_trie/src/lookup.rs
  patricia_trie/src/node.rs
  patricia_trie/src/node_codec.rs
  patricia_trie/src/recorder.rs
  patricia_trie/src/sectriedb.rs
  patricia_trie/src/sectriedbmut.rs
  patricia_trie/src/triedb.rs
  patricia_trie/src/triedbmut.rs
  rlp/Cargo.toml
  rlp/src/impls.rs
  rlp/src/lib.rs
  rlp/src/stream.rs
  rlp/src/traits.rs
  test-support/keccak-hasher/Cargo.toml
  test-support/patricia-trie-ethereum/Cargo.toml
  test-support/patricia-trie-ethereum/src/rlp_node_codec.rs
  trie-standardmap/Cargo.toml
  trie-standardmap/src/lib.rs
  triehash/Cargo.toml
  triehash/src/lib.rs
Labels: A3-inprogress, M4-core

#59 fix accepting malformed rlp packages
  rlp/src/rlpin.rs
  rlp/tests/tests.rs
Labels: A8-looksgood, M4-core

#63 bump smallvec to 0.6
  transaction-pool/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M4-core

#60 fix accepting non-canonical rlp packages
  rlp/src/rlpin.rs
  rlp/tests/tests.rs
Labels: A0-pleasereview, M4-core

#58 Ring 0.13
  parity-crypto/Cargo.toml
Labels: A0-pleasereview, M5-dependencies

#66 Add test for finding common prefix length with concatenated slices
  patricia_trie/src/nibbleslice.rs
Labels: A2-insubstantial, A8-looksgood

#65 added appveyor.yml
  .travis.yml
  README.md
  appveyor.yml
  fixed-hash/src/hash.rs
  uint/Cargo.toml
  uint/src/lib.rs
Labels: A0-pleasereview, M1-ci
