Repository paritytech/parity-common, pull requests merged in 2019-09, with the labels that each got.

#205 [ethbloom, ethereum-types,kvdb] migrate to 2018 edition
  ethbloom/Cargo.toml
  ethbloom/src/lib.rs
  ethereum-types/Cargo.toml
  ethereum-types/benches/bigint.rs
  ethereum-types/src/hash.rs
  ethereum-types/src/lib.rs
  ethereum-types/src/uint.rs
  ethereum-types/tests/serde.rs
  kvdb/Cargo.toml
  kvdb/src/lib.rs
  parity-bytes/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#212 [parity-bytes] alloc crate has stabilized
  .travis.yml
  parity-bytes/Cargo.toml
  parity-bytes/src/lib.rs
Labels: A8-looksgood

#215 [ethbloom] Improve ethbloom
  .travis.yml
  ethbloom/Cargo.toml
  ethbloom/benches/bloom.rs
  ethbloom/benches/unrolling.rs
  ethbloom/src/lib.rs
  fixed-hash/src/lib.rs
Labels: A8-looksgood

#213 [plain_hasher] Migrate to 2018 edition
  .travis.yml
  plain_hasher/Cargo.toml
  plain_hasher/benches/bench.rs
  plain_hasher/src/lib.rs
Labels: A8-looksgood

#206 [rlp] Add no_std support
  .travis.yml
  primitive-types/Cargo.toml
  primitive-types/impls/rlp/Cargo.toml
  primitive-types/impls/rlp/src/lib.rs
  rlp/Cargo.toml
  rlp/benches/rlp.rs
  rlp/src/error.rs
  rlp/src/impls.rs
  rlp/src/lib.rs
  rlp/src/rlpin.rs
  rlp/src/stream.rs
  rlp/src/traits.rs
  rlp/tests/tests.rs
Labels: A8-looksgood

#214 [triehash] Migrate to 2018 edition
  .travis.yml
  triehash/Cargo.toml
  triehash/benches/triehash.rs
  triehash/src/lib.rs
Labels: A8-looksgood

#218 Find PendingIterator in Transaction Pool
  transaction-pool/src/pool.rs
  transaction-pool/src/tests/mod.rs
Labels: A8-looksgood, M4-core

#219 [transaction-pool] Bump version
  transaction-pool/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#221 [kvdb-rocksdb] Migrated code to 2018 edition, updated dependencies
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood

#222 [kvdb-memorydb] Migrated code to 2018 edition, updated parking_lot
  kvdb-memorydb/Cargo.toml
  kvdb-memorydb/src/lib.rs
Labels: A8-looksgood

#202 [kvdb-web] indexeddb implementation
  .travis.yml
  Cargo.toml
  kvdb-web/Cargo.toml
  kvdb-web/src/error.rs
  kvdb-web/src/indexed_db.rs
  kvdb-web/src/lib.rs
  kvdb-web/tests/indexed_db.rs
Labels: A0-pleasereview

#225 [kvdb-web] bump futures-preview to 0.3.0-alpha.18
  kvdb-web/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial, M5-dependencies

#227 Bump parking_lot version
  kvdb-memorydb/Cargo.toml
Labels: A2-insubstantial, A8-looksgood
