Repository paritytech/parity-common, pull requests merged in 2019-12, with the labels that each got.

#274 [kvdb-rocksdb] Use "pinned" gets to avoid allocations
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood

#280 Compile triehash for no_std
  triehash/CHANGELOG.md
  triehash/Cargo.toml
  triehash/src/lib.rs
Labels: A0-pleasereview, M4-core

#275 [kvdb-rocksdb] Add benchmark for point lookups
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/benches/.gitignore
  kvdb-rocksdb/benches/bench_read_perf.rs
Labels: A8-looksgood

#284 Update benchmark code to latest changes on master
  .travis.yml
  kvdb-rocksdb/benches/bench_read_perf.rs
Labels: A0-pleasereview, A2-insubstantial

#277 kvdb-rocksdb: pass ReadOptions to iterators
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview

#285 [kvdb-rocksdb] adds `num_keys()`
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#286 Prepare releases
  fixed-hash/CHANGELOG.md
  fixed-hash/Cargo.toml
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  triehash/CHANGELOG.md
Labels: A0-pleasereview, A2-insubstantial

#290 Move and extend impls for locking primitives
  parity-util-mem/Cargo.toml
  parity-util-mem/src/impls.rs
  parity-util-mem/src/malloc_size.rs
Labels: A0-pleasereview

#292 Add memory stats for kvdb-s
  kvdb-memorydb/Cargo.toml
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/lib.rs
  kvdb-web/Cargo.toml
  kvdb-web/src/lib.rs
  kvdb/Cargo.toml
  kvdb/src/lib.rs
  parity-util-mem/src/malloc_size.rs
  parity-util-mem/tests/derive.rs
Labels: A8-looksgood
