Repository paritytech/parity-common, pull requests merged in 2019-10, with the labels that each got.

#168 Fix deprecation warning
  parity-path/Cargo.toml
  parity-path/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#217 update rand to 0.7 (breaking change)
  contract-address/Cargo.toml
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  fixed-hash/Cargo.toml
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  fixed-hash/src/tests.rs
  keccak-hash/Cargo.toml
  kvdb-rocksdb/Cargo.toml
  primitive-types/Cargo.toml
  rlp/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
Labels: A8-looksgood

#223 [fixed-hash] Migrated code to the 2018 edition and updated dependencies
  fixed-hash/Cargo.toml
  fixed-hash/src/lib.rs
  fixed-hash/src/tests.rs
Labels: A8-looksgood

#243 Fix off-by-one.
  primitive-types/impls/serde/Cargo.toml
  primitive-types/impls/serde/src/serialize.rs
Labels: A8-looksgood

#210 Move ethkey crypto utils to parity crypto crate
  parity-crypto/Cargo.toml
  parity-crypto/benches/bench.rs
  parity-crypto/src/lib.rs
  parity-crypto/src/publickey/ec_math_utils.rs
  parity-crypto/src/publickey/ecdh.rs
  parity-crypto/src/publickey/ecdsa_signature.rs
  parity-crypto/src/publickey/ecies.rs
  parity-crypto/src/publickey/error.rs
  parity-crypto/src/publickey/extended_keys.rs
  parity-crypto/src/publickey/keypair.rs
  parity-crypto/src/publickey/keypair_generator.rs
  parity-crypto/src/publickey/mod.rs
  parity-crypto/src/publickey/secret_key.rs
Labels: A1-onice, M4-core

#246 Use published version for secp crate
  parity-crypto/Cargo.toml
  parity-crypto/src/publickey/error.rs
  parity-crypto/src/publickey/keypair_generator.rs
Labels: A0-pleasereview

#239 Upgrade dependencies
  contract-address/Cargo.toml
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  fixed-hash/Cargo.toml
  keccak-hash/Cargo.toml
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/Cargo.toml
  kvdb-web/Cargo.toml
  kvdb/Cargo.toml
  parity-bytes/Cargo.toml
  parity-crypto/Cargo.toml
  parity-path/Cargo.toml
  parity-util-mem/Cargo.toml
  plain_hasher/Cargo.toml
  primitive-types/Cargo.toml
  primitive-types/impls/codec/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  rlp/Cargo.toml
  trace-time/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
  uint/Cargo.toml
  uint/src/lib.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A8-looksgood

#250 Release impl-rlp 0.2.1
  primitive-types/impls/rlp/Cargo.toml
Labels: A0-pleasereview

#253 Fix `impl-serde::serializa/_raw` for empty slices
  primitive-types/impls/serde/src/serialize.rs
Labels: A8-looksgood
