Repository paritytech/parity-common, pull requests merged in 2019-11, with the labels that each got.

#260 upgrade tiny-keccak to 2.0
  ethbloom/Cargo.toml
  ethbloom/benches/bloom.rs
  ethbloom/src/lib.rs
  keccak-hash/Cargo.toml
  keccak-hash/src/lib.rs
  parity-crypto/Cargo.toml
  parity-crypto/src/lib.rs
  triehash/Cargo.toml
  triehash/benches/triehash.rs
Labels: A0-pleasereview, M5-dependencies

#269 Introduce Rlp::at_with_offset method.
  rlp/src/rlpin.rs
  rlp/tests/tests.rs
Labels: A8-looksgood, M4-core

#256 kvdb-rocksdb: configurable memory budget per column
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview

#259 kvdb-web: async-awaitify
  kvdb-web/Cargo.toml
  kvdb-web/src/lib.rs
  kvdb-web/tests/indexed_db.rs
Labels: A8-looksgood

#268 [fixed-hash]: fix build with `default-features`
  fixed-hash/src/lib.rs
Labels: A8-looksgood

#266 Use 2018 edition for rustfmt
  .travis.yml
  ethbloom/src/lib.rs
  rustfmt.toml
Labels: A8-looksgood, M1-ci

#257 [kvdb-rocksdb] switch to upstream
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview, M4-core, M5-dependencies

#273 [kvdb-rocksdb] Release 0.2
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
Labels: A8-looksgood, M5-dependencies
