Repository paritytech/parity-common, pull requests merged in 2019-05, with the labels that each got.

#85 rust-crypto dependency removal
  parity-crypto/Cargo.toml
  parity-crypto/benches/bench.rs
  parity-crypto/src/aes.rs
  parity-crypto/src/digest.rs
  parity-crypto/src/error.rs
  parity-crypto/src/hmac/mod.rs
  parity-crypto/src/hmac/test.rs
  parity-crypto/src/lib.rs
  parity-crypto/src/pbkdf2/mod.rs
  parity-crypto/src/pbkdf2/test.rs
  parity-crypto/src/scrypt.rs
Labels: A8-looksgood

#132 Bump parity-crypto to 0.3.1
  parity-crypto/Cargo.toml
Labels: A2-insubstantial

#130 Use EntropyRng instead of OsRng
  fixed-hash/src/hash.rs
Labels: A0-pleasereview

#134 Bump fixed-hash to 0.3.2
  fixed-hash/Cargo.toml
Labels: A2-insubstantial

#123 uint: convert benchmarks to criterion
  uint/Cargo.toml
  uint/benches/bigint.rs
Labels: A0-pleasereview

#122 fix rocksdb block cache size
  kvdb-rocksdb/src/lib.rs
Labels: A2-insubstantial

#125 uint: faster mul by u64
  uint/benches/bigint.rs
  uint/src/uint.rs
Labels: A0-pleasereview

#126 uint: faster div
  uint/benches/bigint.rs
  uint/fuzz/.gitignore
  uint/fuzz/Cargo.toml
  uint/fuzz/README.md
  uint/fuzz/fuzz_targets/div_mod.rs
  uint/fuzz/fuzz_targets/div_mod_word.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A0-pleasereview

#140 Replace ring with pbkdf2 for pbkdf2
  parity-crypto/Cargo.toml
  parity-crypto/src/lib.rs
  parity-crypto/src/pbkdf2/mod.rs
  parity-crypto/src/pbkdf2/test.rs
Labels: A8-looksgood

#141 Remove a few intermediate macros
  uint/src/uint.rs
Labels: A2-insubstantial

#142 primitive-types: derive Debug, PartialEq, Eq for Error
  primitive-types/src/lib.rs
Labels: A2-insubstantial

#136 uint: bump version to 0.7
  ethereum-types/Cargo.toml
  primitive-types/Cargo.toml
  uint/Cargo.toml
  uint/README.md
  uint/benches/bigint.rs
Labels: A8-looksgood

#139 Replace ring with hmac for hmacs
  parity-crypto/src/hmac/mod.rs
Labels: A0-pleasereview

#145 Backports from https://github.com/paritytech/primitives/pull/15
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  ethereum-types/tests/serde.rs
  primitive-types/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  primitive-types/impls/serde/src/lib.rs
  primitive-types/impls/serde/src/serialize.rs
Labels: A0-pleasereview

#147 [trie-standardmap] remove from parity-common
  Cargo.toml
  trie-standardmap/Cargo.toml
  trie-standardmap/src/lib.rs
  triehash/Cargo.toml
Labels: A8-looksgood

#154 [parity-bytes] add no-std support
  .travis.yml
  parity-bytes/Cargo.toml
  parity-bytes/README.md
  parity-bytes/src/lib.rs
Labels: A8-looksgood

#162 Remove unused test support files
  test-support/patricia-trie-ethereum/Cargo.toml
  test-support/patricia-trie-ethereum/src/lib.rs
  test-support/patricia-trie-ethereum/src/rlp_node_codec.rs
Labels: A2-insubstantial

#169 Update RLP to 2018 Edition
  rlp/Cargo.toml
  rlp/benches/rlp.rs
  rlp/src/impls.rs
  rlp/src/lib.rs
  rlp/src/rlpin.rs
  rlp/src/stream.rs
  rlp/src/traits.rs
  rlp/tests/tests.rs
Labels: A0-pleasereview, A2-insubstantial

#170 Update transaction-pool to 2018 Edition
  transaction-pool/Cargo.toml
  transaction-pool/src/lib.rs
  transaction-pool/src/listener.rs
  transaction-pool/src/pool.rs
  transaction-pool/src/replace.rs
  transaction-pool/src/scoring.rs
  transaction-pool/src/tests/helpers.rs
  transaction-pool/src/tests/mod.rs
  transaction-pool/src/tests/tx_builder.rs
  transaction-pool/src/transactions.rs
  transaction-pool/src/verifier.rs
Labels: A0-pleasereview, A2-insubstantial

#172 Upgrade to 2018 edition
  parity-crypto/Cargo.toml
  parity-crypto/src/aes.rs
  parity-crypto/src/digest.rs
  parity-crypto/src/error.rs
  parity-crypto/src/hmac/mod.rs
  parity-crypto/src/lib.rs
  parity-crypto/src/pbkdf2/mod.rs
  parity-crypto/src/scrypt.rs
Labels: A0-pleasereview, A2-insubstantial

#175 [uint] migrate to 2018 edition
  uint/Cargo.toml
  uint/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#93 Fix malloc_size_of for mac
  .travis.yml
  parity-util-mem/Cargo.toml
  parity-util-mem/slim_malloc_size_of.patch
  parity-util-mem/src/allocators.rs
  parity-util-mem/src/lib.rs
  parity-util-mem/src/malloc_size.rs
Labels: A0-pleasereview

#94 Remove heapsize
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  fixed-hash/Cargo.toml
  fixed-hash/README.md
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  fixed-hash/src/tests.rs
  keccak-hash/Cargo.toml
  kvdb-rocksdb/Cargo.toml
  parity-util-mem/Cargo.toml
  parity-util-mem/README.md
  parity-util-mem/src/allocators.rs
  parity-util-mem/src/lib.rs
  parity-util-mem/src/malloc_size.rs
  parity-util-mem/src/sizeof.rs
  primitive-types/Cargo.toml
  rlp/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
  uint/Cargo.toml
  uint/README.md
  uint/src/lib.rs
  uint/src/uint.rs
Labels: A8-looksgood
