Repository paritytech/parity-common, pull requests merged in 2019-01, with the labels that each got.

#86 Unify primitive types for Parity Ethereum and Substrate
  Cargo.toml
  primitive-types/Cargo.toml
  primitive-types/impls/codec/Cargo.toml
  primitive-types/impls/codec/src/lib.rs
  primitive-types/impls/rlp/Cargo.toml
  primitive-types/impls/rlp/src/lib.rs
  primitive-types/impls/serde/Cargo.toml
  primitive-types/impls/serde/src/lib.rs
  primitive-types/impls/serde/src/serialize.rs
  primitive-types/src/lib.rs
Labels: A0-pleasereview

#92 Expose U128, add u128 conversions.
  primitive-types/src/lib.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A6-mustntgrumble, A7-looksgoodtestsfail

#89 Initialize a crate for memory related tools
  .travis.yml
  Cargo.toml
  parity-util-mem/Cargo.toml
  parity-util-mem/README.md
  parity-util-mem/get_malloc_size_src.sh
  parity-util-mem/slim_malloc_size_of.patch
  parity-util-mem/src/allocators.rs
  parity-util-mem/src/impls.rs
  parity-util-mem/src/lib.rs
  parity-util-mem/src/malloc_size.rs
  parity-util-mem/src/sizeof.rs
Labels: A8-looksgood

#95 Bump primitive-types and uint version
  primitive-types/Cargo.toml
  uint/Cargo.toml
Labels: A2-insubstantial

#96 docs(uint): U128 + version 0.6.1
  uint/README.md
Labels: A2-insubstantial, A8-looksgood

#97 Move `ethereum-types` to `parity-common` repo and more conversion functions for U128
  Cargo.toml
  ethbloom/Cargo.toml
  ethbloom/benches/bloom.rs
  ethbloom/benches/unrolling.rs
  ethbloom/src/lib.rs
  ethereum-types/Cargo.toml
  ethereum-types/benches/bigint.rs
  ethereum-types/src/hash.rs
  ethereum-types/src/lib.rs
  ethereum-types/src/uint.rs
  primitive-types/Cargo.toml
  primitive-types/src/error.rs
  primitive-types/src/lib.rs
Labels: A0-pleasereview

#83 Documentation fixes
  plain_hasher/Cargo.toml
  plain_hasher/README.md
Labels: A2-insubstantial, M3-docs
