Repository paritytech/parity-common, pull requests merged in 2019-08, with the labels that each got.

#193 Impl encodelike
  primitive-types/Cargo.toml
  primitive-types/impls/codec/Cargo.toml
  primitive-types/impls/codec/src/lib.rs
Labels: A0-pleasereview

#197 Fix compiler error with not being able to resolve types
  uint/Cargo.toml
  uint/src/uint.rs
Labels: A0-pleasereview

#190 [contract-address] extract into a crate
  Cargo.toml
  contract-address/Cargo.toml
  contract-address/README.md
  contract-address/src/lib.rs
Labels: A0-pleasereview

#177 [keccak-hash] Add no_std support, migrate to 2018 edition
  .travis.yml
  keccak-hash/Cargo.toml
  keccak-hash/benches/keccak_256.rs
  keccak-hash/src/lib.rs
Labels: A8-looksgood

#199 [uint] fix outdated README.md
  uint/README.md
Labels: A2-insubstantial, M3-docs

#200 Introduce `ContractAddress` newtype instead of scheme enum
  .travis.yml
  contract-address/Cargo.toml
  contract-address/README.md
  contract-address/src/lib.rs
Labels: A8-looksgood
