Repository paritytech/parity-common, pull requests merged in 2020-07, with the labels that each got.

#403 Port runtime to tokio-compat
  runtime/Cargo.toml
  runtime/examples/simple.rs
  runtime/src/lib.rs
Labels: A8-looksgood

#407 plain_hasher/uint: remove some unsafe code and don't assume endianness
  plain_hasher/src/lib.rs
  uint/src/uint.rs
Labels: A8-looksgood

#408 fix benches in uint and plain_hasher
  plain_hasher/benches/bench.rs
  uint/benches/bigint.rs
Labels: A0-pleasereview, A2-insubstantial

#395 kvdb-rocksdb: set format_version to 5
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview

#410 plain_hasher: remove std feature and unsafe code
  plain_hasher/CHANGELOG.md
  plain_hasher/Cargo.toml
  plain_hasher/src/lib.rs
  uint/CHANGELOG.md
Labels: A0-pleasereview

#409 Add automatic methods to KeyValueDB which test for the existence of certain objects
  kvdb/src/lib.rs
Labels: A0-pleasereview, F8-enhancement

#415 parity-crypto: dependency upgrades to remove block-cipher-trait
  parity-crypto/Cargo.toml
  parity-crypto/src/aes.rs
Labels: A8-looksgood, M5-dependencies
