Repository paritytech/parity-common, pull requests merged in 2020-05, with the labels that each got.

#385 primitive-types: add no_std support for serde feature
  .travis.yml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  primitive-types/impls/serde/src/lib.rs
  primitive-types/impls/serde/src/serialize.rs
Labels: A8-looksgood

#386 prepare new `kvdb-` release
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
Labels: A2-insubstantial

#387 prepare primitive-types release
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  primitive-types/impls/serde/CHANGELOG.md
  primitive-types/impls/serde/Cargo.toml
Labels: A2-insubstantial

#393 Implement codec for ethereum types
  .travis.yml
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethbloom/src/lib.rs
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
  ethereum-types/src/hash.rs
  ethereum-types/src/uint.rs
Labels: A8-looksgood

#389 uint: simplify `Ord` impl
  uint/benches/bigint.rs
  uint/src/uint.rs
Labels: A0-pleasereview, A2-insubstantial

#390 uint: manually implement `Eq` and `Hash`
  uint/CHANGELOG.md
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A0-pleasereview, A2-insubstantial
