Repository paritytech/parity-common, pull requests merged in 2020-04, with the labels that each got.

#370 keccak-hash: add keccak256_range and keccak512_range functions
  keccak-hash/CHANGELOG.md
  keccak-hash/src/lib.rs
Labels: A0-pleasereview

#372 keccak-hash: fix bench and add one for range
  .travis.yml
  keccak-hash/Cargo.toml
  keccak-hash/benches/keccak_256.rs
Labels: A2-insubstantial

#375 parity-util-mem: fix for windows
  appveyor.yml
  parity-util-mem/src/allocators.rs
Labels: A0-pleasereview

#376 bump parity-util-mem
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  parity-util-mem/README.md
Labels: A2-insubstantial

#365 kvdb-rocksdb: optimize and rename iter_from_prefix
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
  kvdb-shared-tests/src/lib.rs
  kvdb-web/src/lib.rs
  kvdb-web/tests/indexed_db.rs
  kvdb/CHANGELOG.md
  kvdb/src/lib.rs
Labels: A0-pleasereview

#378 Add arbitrary trait implementation
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  fixed-hash/Cargo.toml
  fixed-hash/README.md
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  primitive-types/Cargo.toml
  uint/Cargo.toml
  uint/README.md
  uint/src/lib.rs
  uint/src/uint.rs
Labels: A8-looksgood

#368 Fix limit prefix delete case
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
  kvdb-shared-tests/src/lib.rs
  kvdb/src/lib.rs
Labels: A8-looksgood

#381 uint: fix UB in uint::from_big_endian
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A0-pleasereview

#382 prepare releases for a few crates
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
  fixed-hash/CHANGELOG.md
  fixed-hash/Cargo.toml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  uint/CHANGELOG.md
  uint/Cargo.toml
Labels: A2-insubstantial

#379 kvdb-rocksdb: update rocksdb to 0.14
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/iter.rs
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview
