Repository paritytech/parity-common, pull requests merged in 2020-12, with the labels that each got.

#459 rlp: add bytes impls
  rlp/src/impls.rs
  rlp/tests/tests.rs
Labels: A8-looksgood

#463 bump versions and update changelogs
  contract-address/CHANGELOG.md
  contract-address/Cargo.toml
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
  keccak-hash/CHANGELOG.md
  keccak-hash/Cargo.toml
  parity-crypto/CHANGELOG.md
  parity-crypto/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  primitive-types/impls/rlp/CHANGELOG.md
  primitive-types/impls/rlp/Cargo.toml
  rlp/CHANGELOG.md
  rlp/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
Labels: A2-insubstantial

#471 update web dependencies
  kvdb-web/Cargo.toml
Labels: A2-insubstantial, M5-dependencies

#474 ethereum-types/rlp should pull primitive-types/rlp
  ethereum-types/Cargo.toml
Labels: A8-looksgood

#468 uint: optimize FromStr, make it no_std-compatible
  uint/Cargo.toml
  uint/benches/bigint.rs
  uint/src/lib.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: breaking-change

#470 chore(deps): cargo upgrade parking_lot --all
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
Labels: breaking-change

#482 Bump bytes to 1.0
  rlp/Cargo.toml
Labels: breaking-change

#480 Implement Num from num-traits
  ethereum-types/Cargo.toml
  ethereum-types/src/lib.rs
  primitive-types/Cargo.toml
  primitive-types/impls/num-traits/Cargo.toml
  primitive-types/impls/num-traits/src/lib.rs
  primitive-types/src/lib.rs
  uint/src/uint.rs
Labels: A0-pleasereview

#484 parity-crypto: remove UB test
  parity-crypto/src/hmac/test.rs
  rlp/src/traits.rs
Labels: A0-pleasereview

#483 parity-crypto: upgrade deps
  parity-crypto/Cargo.toml
  parity-crypto/src/aes.rs
  parity-crypto/src/digest.rs
  parity-crypto/src/error.rs
  parity-crypto/src/hmac/mod.rs
  parity-crypto/src/pbkdf2/mod.rs
Labels: A0-pleasereview
