Repository paritytech/parity-common, pull requests merged in 2020-03, with the labels that each got.

#356 CI: troubleshoot macOS build
  .travis.yml
Labels: A0-pleasereview, A2-insubstantial, M1-ci

#355 parity-util-mem: use malloc for usable_size on android
  parity-util-mem/src/allocators.rs
Labels: A0-pleasereview

#351 kvdb: remove parity-bytes dependency
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  kvdb/src/lib.rs
Labels: A2-insubstantial, M5-dependencies

#352 parity-util-mem: update mimalloc feature
  parity-util-mem/Cargo.toml
  parity-util-mem/src/allocators.rs
  parity-util-mem/src/lib.rs
Labels: A0-pleasereview, M5-dependencies

#361 Prep for release
  contract-address/CHANGELOG.md
  contract-address/Cargo.toml
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
  fixed-hash/CHANGELOG.md
  fixed-hash/Cargo.toml
  keccak-hash/CHANGELOG.md
  keccak-hash/Cargo.toml
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-bytes/CHANGELOG.md
  parity-bytes/Cargo.toml
  parity-crypto/CHANGELOG.md
  parity-crypto/Cargo.toml
  parity-path/CHANGELOG.md
  parity-path/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  plain_hasher/CHANGELOG.md
  plain_hasher/Cargo.toml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  rlp/CHANGELOG.md
  rlp/Cargo.toml
  trace-time/CHANGELOG.md
  trace-time/Cargo.toml
  transaction-pool/CHANGELOG.md
  transaction-pool/Cargo.toml
  triehash/CHANGELOG.md
  triehash/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#349 Memtest example for Rocksdb
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/examples/memtest.rs
Labels: A8-looksgood

#362 Use correct license ID
  contract-address/Cargo.toml
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  fixed-hash/Cargo.toml
  keccak-hash/Cargo.toml
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/Cargo.toml
  kvdb/Cargo.toml
  parity-bytes/Cargo.toml
  parity-crypto/Cargo.toml
  parity-path/Cargo.toml
  parity-util-mem/Cargo.toml
  parity-util-mem/derive/Cargo.toml
  plain_hasher/Cargo.toml
  primitive-types/Cargo.toml
  primitive-types/impls/codec/Cargo.toml
  primitive-types/impls/rlp/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  rlp-derive/Cargo.toml
  rlp/Cargo.toml
  trace-time/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
  uint/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#363 Ban duplicates of parity-uil-mem from being linked into the same program
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  parity-util-mem/README.md
  parity-util-mem/build.rs
Labels: A0-pleasereview

#313 kvdb: no overlay
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/benches/bench_read_perf.rs
  kvdb-rocksdb/src/lib.rs
  kvdb-shared-tests/src/lib.rs
  kvdb-web/CHANGELOG.md
  kvdb-web/src/lib.rs
  kvdb-web/tests/indexed_db.rs
  kvdb/CHANGELOG.md
  kvdb/src/lib.rs
Labels: A0-pleasereview

#360 Delete by prefix operator in kvdb
  kvdb-memorydb/Cargo.toml
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/lib.rs
  kvdb-shared-tests/Cargo.toml
  kvdb-shared-tests/src/lib.rs
  kvdb-web/Cargo.toml
  kvdb-web/src/indexed_db.rs
  kvdb-web/tests/indexed_db.rs
  kvdb/src/lib.rs
Labels: A8-looksgood
