Repository paritytech/parity-common, pull requests merged in 2020-01, with the labels that each got.

#293 Add memory extensions for LRUCache, hashbrown
  parity-util-mem/Cargo.toml
  parity-util-mem/src/malloc_size.rs
  parity-util-mem/tests/derive.rs
Labels: A0-pleasereview

#300 Use "impl-trait-for-tuples" for tuples in parity-util-mem
  parity-util-mem/Cargo.toml
  parity-util-mem/src/malloc_size.rs
  parity-util-mem/tests/derive.rs
Labels: A8-looksgood

#294 I/O statistic for key-value databases
  kvdb-rocksdb/src/lib.rs
  kvdb-rocksdb/src/stats.rs
  kvdb/src/io_stats.rs
  kvdb/src/lib.rs
Labels: A8-looksgood

#298 Add a top level function to parity-util-mem
  parity-util-mem/src/lib.rs
Labels: A0-pleasereview

#302 Expose to_hex and from_hex from impl-serde
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  primitive-types/Cargo.toml
  primitive-types/impls/serde/Cargo.toml
  primitive-types/impls/serde/src/serialize.rs
Labels: A8-looksgood

#301 extract common kvdb tests into a crate
  Cargo.toml
  kvdb-memorydb/Cargo.toml
  kvdb-memorydb/src/lib.rs
  kvdb-rocksdb/Cargo.toml
  kvdb-rocksdb/src/lib.rs
  kvdb-shared-tests/Cargo.toml
  kvdb-shared-tests/src/lib.rs
  kvdb-web/Cargo.toml
  kvdb-web/tests/indexed_db.rs
Labels: A8-looksgood

#304 kvdb: remove KeyValueDBHandler
  kvdb/src/lib.rs
Labels: A2-insubstantial

#303 Fix typo
  kvdb-rocksdb/src/lib.rs
Labels: A2-insubstantial

#305 Use custom error type for `from_hex`
  kvdb/src/lib.rs
  parity-util-mem/derive/Cargo.toml
  primitive-types/impls/serde/src/serialize.rs
Labels: A8-looksgood

#299 Draft version updates and changelog
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
Labels: A8-looksgood

#308 Use proper memory queries to rocksdb
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood

#307 Update features and feature dependencies
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/Cargo.toml
  kvdb-web/Cargo.toml
  kvdb/Cargo.toml
  parity-util-mem/Cargo.toml
  parity-util-mem/src/ethereum_impls.rs
  parity-util-mem/src/impls.rs
  parity-util-mem/src/lib.rs
  parity-util-mem/src/malloc_size.rs
Labels: A8-looksgood

#315 keccak-hash: switch benches to criterion
  .travis.yml
  ethbloom/src/lib.rs
  fixed-hash/README.md
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  keccak-hash/Cargo.toml
  keccak-hash/benches/keccak_256.rs
  kvdb-rocksdb/Cargo.toml
  parity-crypto/benches/bench.rs
  primitive-types/impls/serde/src/serialize.rs
  rlp/src/lib.rs
  rlp/src/stream.rs
  triehash/src/lib.rs
Labels: A2-insubstantial, A8-looksgood

#316 README: fix appveyor badge
  README.md
Labels: A2-insubstantial

#318 uint: make zero const fn
  uint/src/uint.rs
Labels: A8-looksgood

#319 Expand const fn coverage
  fixed-hash/src/hash.rs
  rlp/src/rlpin.rs
  uint/src/uint.rs
Labels: A8-looksgood
