Repository paritytech/parity-common, pull requests merged in 2020-08, with the labels that each got.

#417 uint: Add checked_pow
  uint/CHANGELOG.md
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A8-looksgood

#418 uint: bump minor version
  uint/CHANGELOG.md
  uint/Cargo.toml
Labels: A2-insubstantial

#419 travis: pin geckodriver in wasm-pack tests
  .travis.yml
Labels: A0-pleasereview

#421 uint: make const matching work again
  uint/CHANGELOG.md
  uint/Cargo.toml
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A0-pleasereview

#423 uint/src/uint.rs: Fix doc comment typo
  uint/src/uint.rs
Labels: A8-looksgood, F5-documentation

#424 kvdb-rocksdb: bump rocksdb, version, update changelog
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial

#425 Fix panic in FromStr implementation
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A8-looksgood

#426 kvdb-rocksdb: do not use deprecated cache option
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview
