Repository paritytech/parity-common, pull requests merged in 2020-06, with the labels that each got.

#397 kvdb-rocksdb: call iter_with_prefix directly on cfs in write
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood

#400 Box secret memory
  parity-crypto/CHANGELOG.md
  parity-crypto/Cargo.toml
  parity-crypto/src/publickey/ec_math_utils.rs
  parity-crypto/src/publickey/ecdh.rs
  parity-crypto/src/publickey/extended_keys.rs
  parity-crypto/src/publickey/keypair.rs
  parity-crypto/src/publickey/mod.rs
  parity-crypto/src/publickey/secret_key.rs
Labels: A8-looksgood

#399 parity-util-mem: export MallocShallowSizeOf
  parity-util-mem/src/lib.rs
Labels: A0-pleasereview, A2-insubstantial

#312 primitive-types: scale-info support
  primitive-types/Cargo.toml
  primitive-types/src/lib.rs
  primitive-types/tests/scale_info.rs
Labels: A0-pleasereview

#402 parity-util-mem: bump version and deps and update changelog
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
Labels: A0-pleasereview, A2-insubstantial
