Repository paritytech/parity-common, pull requests merged in 2020-02, with the labels that each got.

#324 travis: disable kvdb-web tests for chrome
  .travis.yml
Labels: A2-insubstantial, M1-ci

#329 update changelogs
  kvdb-memorydb/CHANGELOG.md
  kvdb-web/CHANGELOG.md
  kvdb/CHANGELOG.md
  parity-util-mem/CHANGELOG.md
Labels: A2-insubstantial, M3-docs

#333 Remove libc completely
  fixed-hash/src/lib.rs
Labels: A8-looksgood

#332 Bump parking_lot to 0.10 and minor versions
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
Labels: A8-looksgood

#258 [parity-crypto] Use upstream secp256k1
  parity-crypto/CHANGELOG.md
  parity-crypto/Cargo.toml
  parity-crypto/src/publickey/ec_math_utils.rs
  parity-crypto/src/publickey/ecdh.rs
  parity-crypto/src/publickey/ecdsa_signature.rs
  parity-crypto/src/publickey/ecies.rs
  parity-crypto/src/publickey/error.rs
  parity-crypto/src/publickey/extended_keys.rs
  parity-crypto/src/publickey/keypair.rs
  parity-crypto/src/publickey/keypair_generator.rs
  parity-crypto/src/publickey/mod.rs
  parity-crypto/src/publickey/secret_key.rs
Labels: A0-pleasereview, F6-refactor, M5-dependencies

#335 Update doc comment
  parity-util-mem/src/malloc_size.rs
Labels: A8-looksgood

#337 [parity crypto]: remove unused dependency `rustc_hex`
  parity-crypto/Cargo.toml
Labels: A2-insubstantial

#339 Disable cache if explicit memory budget=0 passed
  kvdb-rocksdb/src/lib.rs
Labels: A8-looksgood

#271 Parity runtime moved to parity common for publication in crates.io
  Cargo.toml
  runtime/CHANGELOG.MD
  runtime/Cargo.toml
  runtime/README.MD
  runtime/examples/simple.rs
  runtime/src/lib.rs
Labels: A1-onice, A5-grumble

#341 Format for readme and changelog corrected
  runtime/CHANGELOG.md
  runtime/README.md
Labels: A2-insubstantial

#346 Implement Error for FromDecStrErr
  uint/src/uint.rs
Labels: A8-looksgood

#347 kvdb-rocksdb: expose RocksDB stats
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/src/lib.rs
  kvdb-rocksdb/src/stats.rs
Labels: A0-pleasereview
