Repository paritytech/parity-common, pull requests merged in 2021-01, with the labels that each got.

#485 primitive-types: address nits of #480
  ethereum-types/src/lib.rs
  ethereum-types/src/uint.rs
  primitive-types/impls/num-traits/Cargo.toml
  primitive-types/impls/num-traits/src/lib.rs
  primitive-types/src/lib.rs
Labels: A0-pleasereview

#499 triehash: patch release
  triehash/CHANGELOG.md
  triehash/Cargo.toml
Labels: A2-insubstantial

#503 ethereum-types: fix wasm builds for serialize feature
  .travis.yml
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
Labels: A0-pleasereview

#511 remove parity-runtime
  Cargo.toml
  runtime/CHANGELOG.md
  runtime/Cargo.toml
  runtime/README.md
  runtime/examples/simple.rs
  runtime/src/lib.rs
Labels: A2-insubstantial

#510 Update codec and crates depending
  contract-address/CHANGELOG.md
  contract-address/Cargo.toml
  ethbloom/CHANGELOG.md
  ethbloom/Cargo.toml
  ethereum-types/CHANGELOG.md
  ethereum-types/Cargo.toml
  keccak-hash/CHANGELOG.md
  keccak-hash/Cargo.toml
  kvdb-memorydb/CHANGELOG.md
  kvdb-memorydb/Cargo.toml
  kvdb-rocksdb/CHANGELOG.md
  kvdb-rocksdb/Cargo.toml
  kvdb-shared-tests/CHANGELOG.md
  kvdb-shared-tests/Cargo.toml
  kvdb-web/CHANGELOG.md
  kvdb-web/Cargo.toml
  kvdb/CHANGELOG.md
  kvdb/Cargo.toml
  parity-crypto/CHANGELOG.md
  parity-crypto/Cargo.toml
  parity-util-mem/CHANGELOG.md
  parity-util-mem/Cargo.toml
  primitive-types/CHANGELOG.md
  primitive-types/Cargo.toml
  primitive-types/impls/codec/CHANGELOG.md
  primitive-types/impls/codec/Cargo.toml
  primitive-types/tests/scale_info.rs
  rlp/Cargo.toml
  transaction-pool/Cargo.toml
  triehash/Cargo.toml
Labels: breaking-change
