Repository paritytech/parity-common, pull requests merged in 2022-09, with the labels that each got.

#674 Upgrade quickcheck in uint, fixed-hash
  fixed-hash/Cargo.toml
  fixed-hash/src/hash.rs
  uint/Cargo.toml
  uint/src/lib.rs
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: A8-looksgood, breaking-change, changelog

#625 ethereum-types: make ethbloom optional
  ethereum-types/Cargo.toml
  ethereum-types/src/lib.rs
Labels: breaking-change, changelog

#667 kvdb-rocksdb: do not attempt to repair
  kvdb-rocksdb/src/lib.rs
Labels: A0-pleasereview, changelog

#678 parity-util-mem: remove wee_alloc
  parity-util-mem/Cargo.toml
  parity-util-mem/src/allocators.rs
  parity-util-mem/src/lib.rs
Labels: breaking-change, changelog

#682 ethereum-types: add if_ethbloom conditional macro
  ethereum-types/src/lib.rs
Labels: changelog
