Repository paritytech/parity-common, pull requests merged in 2022-02, with the labels that each got.

#622 Bump parity-scale-codec to 3.0.0
  primitive-types/impls/codec/Cargo.toml
Labels: breaking-change

#478 uint: div_mod_word use intrinsic u128 division(#406)
  uint/src/uint.rs
Labels: changelog

#611 uint: Fix overflowing_neg by implementing two's complement
  uint/src/uint.rs
  uint/tests/uint_tests.rs
Labels: changelog

#624 Remove duplicate H128 impl from ethereum-types
  ethereum-types/src/hash.rs
Labels: A8-looksgood, changelog
