Repository paritytech/parity-common, pull requests merged in 2023-07, with the labels that each got.

#726 Feature: Make U256::to_f64_lossy more accurate
  primitive-types/src/fp_conversion.rs
Labels: changelog

#766 fix(rlp): `len()` changes as `RlpIterator` is consumed
  rlp/src/rlpin.rs
  rlp/tests/tests.rs
Labels: A8-looksgood, changelog

#767 Fixed clippy::incorrect_clone_impl_on_copy_type in fixed-hash
  fixed-hash/src/hash.rs
Labels: A2-insubstantial
